-- Fidan Business Management — Supabase sxemi
-- Supabase → SQL Editor → New query → bu faylı yapışdırın → Run.
-- Təkrar işə salmaq təhlükəsizdir.

create table if not exists public.orders (
  id                bigint generated by default as identity primary key,
  order_date        date          not null,
  order_email       text          not null,
  order_for_name    text          not null,
  order_price       numeric(10,2) not null check (order_price >= 0),
  delivery_received boolean       not null default false,
  return_request    boolean       not null default false,
  cargo             text          check (cargo in ('Aramex', 'Cargomax')),
  customer_notes    text[]        not null default '{}',
  -- MockAPI-dən köçürülmüş sifarişin köhnə id-si (təkrar köçürmənin qarşısını alır)
  legacy_id         text          unique,
  created_at        timestamptz   not null default now()
);

-- Mağaza (Shein / iHerb). Köhnə bazalarda sütunu sonradan əlavə edir.
alter table public.orders
  add column if not exists store text not null default 'shein'
  check (store in ('shein', 'iherb'));

-- Qazanc: hər sifariş üçün, mağazanın valyutasında (boş = hələ yazılmayıb).
alter table public.orders add column if not exists profit numeric(10,2);

-- Təhvil tarixi: aylıq $300 limiti bağlamanın gəldiyi aya görə hesablanır.
alter table public.orders add column if not exists delivered_at date;

-- Qaytarılma yalnız təhvil alınmış sifarişdə ola bilər.
alter table public.orders drop constraint if exists orders_return_requires_delivery;
alter table public.orders add constraint orders_return_requires_delivery
  check (not return_request or delivery_received);

-- Sifarişin sahibi (login olmuş istifadəçi). Yeni sifarişlərdə avtomatik doldurulur.
alter table public.orders
  add column if not exists user_id uuid default auth.uid() references auth.users (id);
-- Sahibsiz köhnə sifarişlər ilk yaradılmış istifadəçiyə yazılır.
update public.orders
  set user_id = (select id from auth.users order by created_at limit 1)
  where user_id is null;
alter table public.orders alter column user_id set not null;
create index if not exists orders_user_store_date_idx on public.orders (user_id, store, order_date desc, id desc);

create index if not exists orders_order_date_idx on public.orders (order_date desc, id desc);
create index if not exists orders_store_date_idx on public.orders (store, order_date desc, id desc);

-- Hər istifadəçi yalnız ÖZ sifarişlərini görür və dəyişir (panellər bir-birinə qarışmır).
alter table public.orders enable row level security;

drop policy if exists "Signed-in users manage orders" on public.orders;
drop policy if exists "Users manage own orders" on public.orders;
create policy "Users manage own orders"
  on public.orders
  for all
  to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

revoke all on public.orders from anon;
grant select, insert, update, delete on public.orders to authenticated;
grant usage, select on sequence public.orders_id_seq to authenticated;
