-- Fidan Business Management — Supabase sxemi
-- Supabase → SQL Editor → New query → bu faylı yapışdırın → Run.
-- Təkrar işə salmaq təhlükəsizdir.

create table if not exists public.orders (
  id                bigint generated by default as identity primary key,
  order_date        date          not null,
  order_email       text          not null,
  order_for_name    text          not null,
  order_price       numeric(10,2) not null check (order_price >= 0),
  delivery_received boolean       not null default false,
  return_request    boolean       not null default false,
  cargo             text          check (cargo in ('Aramex', 'Cargomax')),
  customer_notes    text[]        not null default '{}',
  -- MockAPI-dən köçürülmüş sifarişin köhnə id-si (təkrar köçürmənin qarşısını alır)
  legacy_id         text          unique,
  created_at        timestamptz   not null default now()
);

-- Mağaza (Shein / iHerb). Köhnə bazalarda sütunu sonradan əlavə edir.
alter table public.orders
  add column if not exists store text not null default 'shein'
  check (store in ('shein', 'iherb'));

-- Qazanc: hər sifariş üçün, mağazanın valyutasında (boş = hələ yazılmayıb).
alter table public.orders add column if not exists profit numeric(10,2);

create index if not exists orders_order_date_idx on public.orders (order_date desc, id desc);
create index if not exists orders_store_date_idx on public.orders (store, order_date desc, id desc);

-- Yalnız daxil olmuş (login) istifadəçi sifarişləri görə və dəyişə bilər.
alter table public.orders enable row level security;

drop policy if exists "Signed-in users manage orders" on public.orders;
create policy "Signed-in users manage orders"
  on public.orders
  for all
  to authenticated
  using (true)
  with check (true);

revoke all on public.orders from anon;
grant select, insert, update, delete on public.orders to authenticated;
grant usage, select on sequence public.orders_id_seq to authenticated;
